### ISSUE TITLE
Chill radio not working

### ISSUE THREAD

**Issue by Yoanndp** [nbirdmann/birdman_radio#1]
Hi @nbirdmann,

Thanks for creating this repo, which allows me to listen to the stations I used to listen on weboasis. However, I notice that the "Chill" radio is not working. Looking at the console, I noticed that "chillprem1" (http://tunein4.streamguys1.com/chillprem1) was not responding anymore. Do you have an alternative to suggest?

Thanks in advance!

**Comment by nbirdmann** [comment]
https://rfcmedia.streamguys1.com/chillpremium.mp3
Should be fixed now thanks 😊
